version: 2.1

jobs:
  py37_linux:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: "Preparing environment"
          command: |
            sudo pip install nox
      - run:
          name: "Testing PyTouch"
          command: |
              pip install nox
              nox

workflows:
  version: 2
  build:
    jobs:
      - py37_linux
