# @package _global_
model:
  _target_: models.touch_detect.TouchDetectionModel
  pre_trained: True
  n_classes: 2
data:
  _target_: datamodules.touch_detect.TouchDetectDataModule
  path: "~/Development/datasets/PyTouch/touch_detect"

  # exclude: ["video", "D00004", "D00003", "D00025", "D00022", "no_sn", "D00001_gel1","D00001_gel2","D00001_gel3","D00002_gel4","D00002_gel5","D00002_gel6","gel_1","gel_2","gel_3","gel_4","gel_5","gel_6","gel_vga", "gelsight"]

  # exclude: ["D00001_gel1","D00001_gel2","D00001_gel3","D00002_gel4","D00002_gel5","D00002_gel6","gel_1","gel_2","gel_3","gel_4","gel_5","gel_6","gel_vga",]

  # digit med
  exclude: ["D00002_gel4","D00002_gel5","D00002_gel6","gel_1","gel_2","gel_3","gel_4","gel_5","gel_6","gel_vga", "omnitact", "gelsight"]

  # digit large
  # exclude: ["gel_1","gel_2","gel_3","gel_4","gel_5","gel_6", "omnitact", "gelsight"]
  #"gelsight","omnitact"]
  transform:
    scales: [64, 64]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
optimizer:
  type: "Adam"
  lr: 0.00847
  lr_patience: 5
  weight_decay: 1.0115995395401329e-08
training:
  seed: 42
  batch_size: 64
  n_threads: 12
  gpu_ids: 1
  n_epochs: 100
  train_val_ratio: 0.75
  pin_memory: 1
checkpoints:
  path: "./checkpoints/"
  last_epoch: "last_epoch.chkpt"
  temp_epoch: "last_epoch.chkpt.tmp"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 10
  restore_best: 1
  csv_file_name: "training_log.csv"
  save_weights_only: True
general:
  verbose: True
  tb_log_path: "./tb_logs/"
